ratings:
  namespace: student75-bookinfo-uat
  image: ghcr.io/pooripro/bookinfo-ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-uat-ratings-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student75/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017/ratings
  COMMIT_SHA: CHANGEME